server.port=8081

camunda.client.zeebe.gateway-url=http://localhost:26500
camunda.client.zeebe.rest-url=http://localhost:8080
camunda.client.auth.token-url=http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/token
camunda.client.auth.client-id=orchestration
camunda.client.auth.client-secret=secret

logging.level.io.camunda=INFO
