camunda:
  identity:
    base-url: http://identity:8084/
    issuer: "http://${HOST:localhost}:18080/auth/realms/camunda-platform"
    issuerBackendUrl: "http://${KEYCLOAK_HOST:host.docker.internal}:18080/auth/realms/camunda-platform"
    type: KEYCLOAK
  modeler:
    pusher:
      host: web-modeler-websockets
      port: 8060
      app-id: "${WEBMODELER_PUSHER_APP_ID:web-modeler-app}"
      key: "${WEBMODELER_PUSHER_KEY}"
      secret: "${WEBMODELER_PUSHER_SECRET}"
    security:
      jwt:
        issuer:
          backend-url: "http://${KEYCLOAK_HOST:host.docker.internal}:18080/auth/realms/camunda-platform"
        audience:
          internal-api: web-modeler-api
          public-api: web-modeler-public-api
    mail:
      from-address: "${WEBMODELER_MAIL_FROM_ADDRESS:noreply@camunda.example.com}"
    server:
      url: http://localhost:8070

spring:
  profiles:
    include: default-logging
  datasource:
    url: "jdbc:postgresql://web-modeler-db:5432/${WEBMODELER_DB_NAME:web-modeler-db}"
    username: "${WEBMODELER_DB_USER:web-modeler-db-user}"
    password: "${WEBMODELER_DB_PASSWORD}"
  mail:
    host: mailpit
    port: 1025
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
      mail.smtp.starttls.required: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://${HOST:localhost}:18080/auth/realms/camunda-platform"
          jwk-set-uri: "http://${KEYCLOAK_HOST:host.docker.internal}:18080/auth/realms/camunda-platform/protocol/openid-connect/certs"

management:
  endpoints:
    web:
      exposure:
        include: health,configprops,info
  endpoint:
    configprops:
      show-values: ALWAYS
    health:
      probes:
        enabled: true

logging:
  level:
    io.camunda.modeler: DEBUG