name: Add new Issue

on:
  issues:
    types:
      - opened
      - transferred

jobs:
  add-to-project:
    name: Add new issue
    runs-on: ubuntu-latest
    steps:
      - name: Create URL to the run output
        id: vars
        run: |
          echo "project_id=33" >> "$GITHUB_OUTPUT"
          echo "now=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@892a26828f195e65540a40b4768ae4571f51ebfc # v4.0.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/data/products/distribution/ci GH_APP_ID_DISTRO_CI;
            secret/data/products/distribution/ci GH_APP_PRIVATE_KEY_DISTRO_CI;
          exportEnv: true

      - name: Generate GitHub token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: generate-github-token
        with:
          app-id: ${{ env.GH_APP_ID_DISTRO_CI }}
          private-key: ${{ env.GH_APP_PRIVATE_KEY_DISTRO_CI }}
      
      - name: Add to Distribution Team project
        uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd # v2.0.0
        with:
          project-url: https://github.com/orgs/camunda/projects/33
          github-token: '${{ steps.generate-github-token.outputs.token }}'

      - name: Update Created At field
        uses: github/update-project-action@af4f6083118f5080c89828b421ef598d1906fb60 # main
        id: update-created-at
        with:
          github_token: ${{ steps.generate-github-token.outputs.token }}
          organization: ${{ github.repository_owner }}
          project_number: ${{ steps.vars.outputs.project_id }}
          content_id: ${{ github.event.issue.node_id }}
          field: Created At
          value: ${{ steps.vars.outputs.now }}

          
